### ISSUE TITLE
Acessing data on figshare

### ISSUE THREAD

**Issue by mariuskempf** [ShahinSHH/COVID-CT-MD#2]
Heyhey!
I am wondering how to access the data shared on figshare? It seems to be a private dataset and I can not find a way to ask for permission or something.

**Comment by ShahinSHH** [comment]
Hello,

You can't search the dataset at the Figshare but it's accessible through the shared link. I checked by several devices and could access and download the dataset.
As an update: this dataset is accepted to publish at the Nature Scientific Data and it may have caused some restrictions for further technical checks. However, I can access it with no problem.

**Comment by mariuskempf** [comment]
Hi - alright. everything works. Sorry, that was a too-quick shot from my side! Thanks a lot 👍
