### ISSUE TITLE
Data download link

### ISSUE THREAD

**Issue by dazzag24** [ShahinSHH/COVID-CT-MD#4]
Hi, 

I am using this link:  https://figshare.com/s/c20215f3d42c98f09ad0 

But cannot see any download link:

![image](https://user-images.githubusercontent.com/1055831/128691982-a31038c1-b0c3-46b4-a84a-497999332dc5.png)

Please advise how to access the data?

Many thanks

**Comment by ShahinSHH** [comment]
> Hi,
> 
> I am using this link: https://figshare.com/s/c20215f3d42c98f09ad0
> 
> But cannot see any download link:
> 
> ![image](https://user-images.githubusercontent.com/1055831/128691982-a31038c1-b0c3-46b4-a84a-497999332dc5.png)
> 
> Please advise how to access the data?
> 
> Many thanks

Hello,
Download links should be at the bottom of the page below the section you took the screenshot. If still not available, please try the following links and let me know if they're working for you or not.

Link to the dataset: https://figshare.com/articles/dataset/COVID-CT-MD_COVID-19_Computed_Tomography_Scan_Dataset_Applicable_in_Machine_Learning_and_Deep_Learning/12991592?backTo=/s/c20215f3d42c98f09ad0?backTo=/s/c20215f3d42c98f09ad0

Link to the statistical analysis code: https://figshare.com/articles/software/Statistical_Analysis_and_Visualization_Code/14125673?backTo=/s/c20215f3d42c98f09ad0?backTo=/s/c20215f3d42c98f09ad0

**Comment by dazzag24** [comment]
Hi,

My bad.  Found them now.  I honestly thought these were figma UI suggesting other similar datasets that I would be interested in.  Didn't think these were the actual download links.

Thanks

Darren
